export const STATISTIC_USER_ALL_GET: string = "STATISTIC_USER_ALL_GET";
export const STATISTIC_USER_ALL_GET_SUCCESS: string = "STATISTIC_USER_ALL_GET_SUCCESS";
export const STATISTIC_USER_ALL_GET_FAIL: string = "STATISTIC_USER_ALL_GET_FAIL";