export const CATEGORIES_ALL_GET: string = "CATEGORIES_ALL_GET";
export const CATEGORIES_ALL_GET_SUCCESS: string = "CATEGORIES_ALL_GET_SUCCESS";
export const CATEGORIES_ALL_GET_FAIL: string = "CATEGORIES_ALL_GET_FAIL";