export const TRANSACTIONS_USER_ALL_GET: string = "TRANSACTIONS_USER_ALL_GET";
export const TRANSACTIONS_USER_ALL_GET_SUCCESS: string = "TRANSACTIONS_USER_ALL_GET_SUCCESS";
export const TRANSACTIONS_USER_ALL_GET_FAIL: string = "TRANSACTIONS_USER_ALL_GET_FAIL";