export const TRANSACTIONS_USER_ALL_GET: string = "TRANSACTIONS_USER_ALL_GET";
export const TRANSACTIONS_USER_ALL_GET_SUCCESS: string = "TRANSACTIONS_USER_ALL_GET_SUCCESS";
export const TRANSACTIONS_USER_ALL_GET_FAIL: string = "TRANSACTIONS_USER_ALL_GET_FAIL";

export const TRANSACTION_GET: string = "TRANSACTION_GET";
export const TRANSACTION_GET_SUCCESS: string = "TRANSACTION_GET_SUCCESS";
export const TRANSACTION_GET_FAIL: string = "TRANSACTION_GET_FAIL";

export const TRANSACTIONS_IMPORT: string = "TRANSACTIONS_IMPORT";
export const TRANSACTIONS_IMPORT_SUCCESS: string = "TRANSACTIONS_IMPORT_SUCCESS";
export const TRANSACTIONS_IMPORT_FAIL: string = "TRANSACTIONS_IMPORT_FAIL";